[project]
name = "pyarrow-exercises"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Tyler White"},
]
dependencies = [
  "pyarrow==18.1.0"
]

[project.optional-dependencies]
dev = [
  "ipykernel==6.29.5",
  "ipython==8.30.0",
  "pre-commit==4.0.1",
  "pytest==8.3.3",
]
